badge component design
ahmetatar/component-design-sample pull request #14
Opened 2022-04-13 12:20 UTC by HusnucanD

Designed Badge Component.

2022-04-13 13:13 UTC, ahmetatar requested changes
Overall good but needs some changes ;)

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.models.ts
> +export const BadgeShapesValues = ['', 'rounded-pill'] as const;
Why do you export the values as a const first and then define a type from them?

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.html
> +  <ng-content></ng-content>
Would it make sense to put an html element other than text in a badge content? Why don't we just put text?

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.ts
> +  styleUrls: ['./badge.component.scss']
In order to override the styles of the components outside of the component, we need to set ViewEncapsulation.None.

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() options: Partial<BadgeOptions> = {};
Options must be nullable

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() options: Partial<BadgeOptions> = {};
Options must be nullable

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() color: BadgeColors = "bg-primary";
Formatting not working? Single quotes in some places and double quotes in other places are inconsistent

2022-04-13 13:13 UTC, ahmetatar commented on src/app/shared/components/badge/badge.stories.ts
> +  options: {}
You should delete what you don't use

2022-04-13 13:29 UTC, HusnucanD commented on src/app/shared/components/badge/badge.models.ts
> +export const BadgeShapesValues = ['', 'rounded-pill'] as const;
In stories, to be able to make selection of components' inputs in a dropdown in storybook UI, I need to set values which will be selected in the dropdown, so I need to use this array in stories.ts file, so I thought that would be better, if there is only one source which is used both in model.ts and stories.ts.

2022-04-13 13:43 UTC, HusnucanD commented on src/app/shared/components/badge/badge.stories.ts
> +  options: {}
Deeleted it, ty.

2022-04-13 13:43 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() color: BadgeColors = "bg-primary";
Changed it, ty.

2022-04-13 13:43 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() options: Partial<BadgeOptions> = {};
Changed it, ty.

2022-04-13 13:43 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.ts
> +  styleUrls: ['./badge.component.scss']
Changed it, ty.

2022-04-13 13:43 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.html
> +  <ng-content></ng-content>
I used input instead of this, ty

2022-04-14 06:39 UTC, HusnucanD commented on src/app/shared/components/badge/badge.models.ts
> +export const BadgeShapesValues = ['', 'rounded-pill'] as const;
You're right, I changed it, ty

2022-04-16 11:12 UTC, ahmetatar reviewed
There are still some things you need to change ;)

2022-04-18 06:11 UTC, HusnucanD commented on src/app/shared/components/badge/badge.stories.ts
> +      options: [
Changed it, ty.

2022-04-18 06:11 UTC, HusnucanD commented on src/app/shared/components/badge/badge.stories.ts
> +  template: `<desx-badge [text]="text" [color]="color" [shape]="shape"
Used it, ty.

2022-04-18 06:11 UTC, HusnucanD commented on src/app/shared/components/badge/badge.stories.ts
> +export const Default = Template.bind({});
Changed it, ty.

2022-04-18 06:11 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.ts
> +  @Input() options?: Partial<BadgeOptions>;
Changed it, ty.

2022-04-18 06:24 UTC, ahmetatar approved these changes

2022-04-18 06:28 UTC, ahmetatar submitted a review, later dismissed
Good job ;)

2022-04-18 10:06 UTC, closed without merging