feat: button group component design
ahmetatar/component-design-sample pull request #15
Opened 2022-04-14 11:54 UTC by volkangurenekli

2022-04-14 12:21 UTC, ahmetatar requested changes
Looks very good overall but some changes are needed

2022-04-14 12:21 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.ts
> +    this.renderer.listen(this.elRef.nativeElement, 'click', (e) => this.click.emit(e));
Why did you use a renderer here? You can make event binding to an element in the template.

2022-04-14 12:21 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.stories.ts
> +    <button type="button" class="btn btn-primary">Left</button>
How do these work with the desx-buttons?

2022-04-14 12:21 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.stories.ts
> +  options: {
Isn't the default value already false?

2022-04-14 12:21 UTC, ahmetatar commented on src/app/shared/components/button-group/pipes/button-group-style.pipe.spec.ts
> +  it('transforms button class name by outline option', () => {
Don't leave the evidence lying around when Copy/Paste ;)

2022-04-14 13:35 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.ts
> +    this.renderer.listen(this.elRef.nativeElement, 'click', (e) => this.click.emit(e));
renderer removed

2022-04-14 13:35 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.stories.ts
> +    <button type="button" class="btn btn-primary">Left</button>
buttons changed

2022-04-14 13:37 UTC, volkangurenekli commented on src/app/shared/components/button-group/pipes/button-group-style.pipe.spec.ts
> +  it('transforms button class name by outline option', () => {
every crime leaves a trace :)

2022-04-15 05:16 UTC, ahmetatar reviewed
Let's discuss for some changes

2022-04-15 05:16 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.html
> +  <ng-content></ng-content>
What can be inside the button group other than the button? If this is an ng-content I can give the button group any component as content. Does your view support this?

2022-04-15 05:16 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.ts
> +  size: ButtonGroupSizes = 'btn-lg';
I'm concerned about the Bootstrap class names getting scattered around the component scope. Can you start a discussion about it?

2022-04-19 08:58 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.html
> +  <ng-content></ng-content>
conditional render added

2022-04-19 08:59 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.ts
> +  size: ButtonGroupSizes = 'btn-lg';
button group model updated

2022-04-20 06:56 UTC, closed without merging