feat(cds-1003): button group component designed
ahmetatar/component-design-sample pull request #19
Opened 2022-04-25 12:12 UTC by volkangurenekli

2022-04-26 04:22 UTC, ahmetatar requested changes
Looks good but you need to change somethings 👍

2022-04-26 04:22 UTC, ahmetatar commented on package.json
> +    "ng-mocks": "^13.4.2",
Before deciding to use a new package, we need to discuss together ;)

2022-04-26 04:22 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.scss
> +  border-top-left-radius: 0;
Why do you need to do something like this for buttons? Doesn't the button group already do this? Also all css rules should be gathered under desx-button-group.

2022-04-26 04:22 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.scss
> +  border-top-left-radius: 0;
Why do you need to do something like this for buttons? Doesn't the button group already do this? Also all css rules should be gathered under desx-button-group.

2022-04-26 04:22 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const rawHtml = MockRender<ButtonComponent>(
Why did you need to do such a thing?

2022-04-26 04:22 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const rawHtml = MockRender<ButtonComponent>(
Why did you need to do such a thing?

2022-04-28 06:16 UTC, volkangurenekli commented on package.json
> +    "ng-mocks": "^13.4.2",
ng-mocks library removed

2022-04-28 06:16 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.scss
> +  border-top-left-radius: 0;
fixed

2022-04-28 06:18 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const rawHtml = MockRender<ButtonComponent>(
MockRender function removed

2022-04-28 06:18 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const rawHtml = MockRender<ButtonComponent>(
MockRender function removed

2022-04-28 08:35 UTC, ahmetatar requested changes
One last change :)

2022-04-28 08:35 UTC, ahmetatar commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const buttonGroup = buttonGroupComponentFixture.getButtonGroup()?.innerHTML;
Here you can have an undefined value. So you should have an expectation to check this

`expect(buttonGroup).toBeTruthy();`

2022-04-28 08:56 UTC, volkangurenekli commented on src/app/shared/components/button-group/button-group.component.spec.ts
> +    const buttonGroup = buttonGroupComponentFixture.getButtonGroup()?.innerHTML;
fixed

2022-05-02 13:02 UTC, merged