feat(cds-1004): badge component designed
ahmetatar/component-design-sample pull request #20
Opened 2022-04-26 08:20 UTC by HusnucanD

feat(cds-1004): badge component designed

2022-04-26 08:46 UTC, ahmetatar requested changes
Let's talk about tests and component features

2022-04-26 08:46 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.spec.ts
> +    for (let i = 0; i < BadgeColorsValues.length; i++) {
You don't need to do this for every color. Also at the end of the day you only test the last one :)

2022-04-26 08:46 UTC, ahmetatar commented on src/app/shared/components/badge/badge.component.spec.ts
> +  it('should show inputted text', () => {
![image](https://user-images.githubusercontent.com/3602465/165259872-f1eb4dc2-a596-4945-9017-b15ae15b24c4.png) ![image](https://user-images.githubusercontent.com/3602465/165260003-a2b4bebb-3cd4-4b8e-b2b7-35c6bcc3ea62.png)

Can't I use a badge like this? Does the component not support this?

2022-04-26 12:32 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.spec.ts
> +  it('should show inputted text', () => {
It does, but this spec checks if the text is rendered in case if it's inputted. If no text is entered, still it can be used.

2022-04-26 12:35 UTC, HusnucanD commented on src/app/shared/components/badge/badge.component.spec.ts
> +    for (let i = 0; i < BadgeColorsValues.length; i++) {
I fixed the error which makes code return only the last one's result

2022-05-13 10:54 UTC, ahmetatar approved these changes

2022-05-13 10:54 UTC, merged